name: Pytest
on: push
jobs:
    pytest-job:
        name: Pytest job
        runs-on: ubuntu-latest
        python-version: 3.6
        steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
        - name: Run tests
          run: pytest

